# Generated by Django 3.1.2 on 2020-10-06 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tracks.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.CharField(default=tracks.utils.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('deezer_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('cover_big', models.TextField(blank=True, null=True)),
                ('cover_medium', models.TextField(blank=True, null=True)),
                ('cover_small', models.TextField(blank=True, null=True)),
                ('cover_xl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(default=tracks.utils.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('deezer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('picture', models.TextField(blank=True, null=True)),
                ('picture_small', models.TextField(blank=True, null=True)),
                ('picture_medium', models.TextField(blank=True, null=True)),
                ('picture_big', models.TextField(blank=True, null=True)),
                ('picture_xl', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.CharField(default=tracks.utils.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('deezer_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('picture', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.CharField(default=tracks.utils.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('deezer_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('preview', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracks.artist'),
        ),
        migrations.AddField(
            model_name='album',
            name='genres',
            field=models.ManyToManyField(to='tracks.Genre'),
        ),
    ]
