# Generated by Django 3.1.2 on 2020-10-05 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='track',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
