# Generated by Django 3.1.2 on 2020-10-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20201005_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='title',
            field=models.CharField(default='undefined', max_length=500),
        ),
    ]
