# Generated by Django 3.1.2 on 2020-10-07 11:31

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.CharField(default=users.models.generateUserId, max_length=17, primary_key=True, serialize=False),
        ),
    ]
