# Generated by Django 3.1.2 on 2020-10-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201007_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(error_messages={'unique': 'A user with that email already exists.'}, max_length=200, unique=True),
        ),
    ]
