# Generated by Django 3.1.5 on 2021-01-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201017_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.TextField(default='/media/users/avatars/default.png'),
        ),
    ]
