# Generated by Django 3.1.5 on 2021-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_account_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.TextField(default='/users/avatars/default.png'),
        ),
    ]
