# Generated by Django 3.1.2 on 2020-10-25 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TracksPlaylist',
            fields=[
                ('id', models.CharField(default=users.models.generateUserId, editable=False, max_length=17, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tracks', models.ManyToManyField(to='tracks.Track')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tracksplaylist',
            constraint=models.UniqueConstraint(fields=('author', 'title'), name='unique-title-playlist-for-creator'),
        ),
    ]
