# Generated by Django 3.1.2 on 2020-10-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0004_auto_20201025_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracksplaylist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
